<!--<a href="offer.html"><img src="public/main/images/download.png" class="img-head" alt=""></a>-->

	<div class="header">

		<div class="container">
			<div class="cart" >					
				<span class="fa fa-shopping-cart my-cart-icon"><span class="badge badge-notify my-cart-badge"></span></span><br />
			</div>			
			<div class="logo">
			<a href="<?php echo URL; ?>"><img src="<?php echo URL; ?>public/item/images/n2print3.png" id="logosize" /></a><br />
			<h1 ><a href="<?php echo URL; ?>"><!--<b>T<br>H<br>E</b>-->N2 Print<span>Online Printing 24 Hours</span></a></h1>
					 
			</div>

			<div class="search-form">
				<form action="search" method="post">
					<input type="text" placeholder="Search..." name="keywords" value="">
					<input type="submit" value=" " >
				</form>
			</div>	

			
			<div class="head-t">
				<ul class="card">
					<li><a href="" ><i class="fa fa-heart" aria-hidden="true"></i>Wishlist</a></li>
					<li><a href="" ><i class="fa fa-user" aria-hidden="true"></i>Login</a></li>
					<li><a href="" ><i class="fa fa-arrow-right" aria-hidden="true"></i>Create Account</a></li>
					<li><a href="" ><i class="fa fa-file-text-o" aria-hidden="true"></i>Order History</a></li>
					<li><a href="" ><i class="fa fa-ship" aria-hidden="true"></i>Shipping</a></li>
				</ul>	

			</div>

			<div class="header-ri">
				<ul class="social-top">
					<li><a href="#" class="icon facebook"><i class="fa fa-facebook" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon twitter"><i class="fa fa-twitter" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon pinterest"><i class="fa fa-pinterest-p" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i><span></span></a></li>
				</ul>	
			</div>
