<?php Session::init(); ?>
<body>
<!--<a href="offer.html"><img src="public/main/images/download.png" class="img-head" alt=""></a>-->

	<div class="header">

		<div class="container">
			<div class="cart" >					
				<span class="fa fa-shopping-cart my-cart-icon"><span class="badge badge-notify my-cart-badge"></span></span><br />
			</div>			
			<div class="logo">
			<a href="<?php echo URL; ?>"><img src="<?php echo URL; ?>public/item/images/n2print3.png" id="logosize" /></a><br />
			<h1 ><a href="<?php echo URL; ?>"><!--<b>T<br>H<br>E</b>--><span>Online Printing 24 Hours</span></a></h1>
					 
			</div>

			<!--<div class="search-form">
				<form action="search" method="post">
					<input type="text" placeholder="Search..." name="keywords" value="">
					<input type="submit" value=" ">
				</form>
			</div>-->	

			<script language="javascript" type="text/javascript">
                            var clientip = localStorage.getItem("clientip"); 
			</script>

			<div class="head-t">
				<ul class="card">
					<?php if (Session::get('loggedIn') == true):?>		
					<li><a href="<?php echo URL; ?>client_login/logout" ><i class="fa fa-user" aria-hidden="true"></i>Logout</a></li>
					<li><a href="myacc" ><i class="fa fa-arrow-right" aria-hidden="true"></i><?php echo Session::get('fname')." ".Session::get('lname'); ?> Account</a></li>
					<?php else: ?>
					<li><a href="client_login" ><i class="fa fa-user" aria-hidden="true"></i>Login</a></li>
					<li><a href="create" ><i class="fa fa-arrow-right" aria-hidden="true"></i>Create an Account</a></li>
					<?php endif; ?>					
					
					<li><a href="cart/cart/" onclick="location.href=this.href+''+clientip;return false;" ><i class="fa fa-shopping-cart" aria-hidden="true"></i>Shopping Cart</a></li>
					<li><a href="<?php echo URL; ?>checkout" ><i class="fa fa-money" aria-hidden="true"></i>Checkout</a></li>
				</ul>	

			</div>

			<div class="header-ri">
				<!--<ul class="social-top">
					<li><a href="#" class="icon facebook"><i class="fa fa-facebook" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon twitter"><i class="fa fa-twitter" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon pinterest"><i class="fa fa-pinterest-p" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i><span></span></a></li>
				</ul>-->	
			</div>
