<?php $id = Session::get('id'); ?>
<style>

*[role="form"] {
    max-width: 60%;
    padding: 15px;
    margin: 0 auto;
    /*background-color: #fff;*/
    border-radius: 0.3em;
}

*[role="form"] h2 {
    margin-left: 5em;
    margin-bottom: 1em;
}

</style>

<div class="container">

  <div class="col-lg-12 well">

    <form class="form-horizontal" role="form" action="../../editacc/editSave/<?php echo $id; ?>" method="post">
                <h2>My Account Information</h2>
                <p>&nbsp;</p>
                <p>&nbsp;</p>

                <!-- /.form-group -->
                
                <div class="form-group">
					<label for="firstName" class="col-sm-3 control-label">* First Name:</label>
                    <div class="col-sm-9">
                        <input type="text" id="firstName" name="fname" value="<?php echo $this->customer['fname']; ?>" class="form-control" autofocus required>
                   </div>
			</div>
			<div class="form-group">
				<label for="firstName" class="col-sm-3 control-label">* Last Name:</label>
                    <div class="col-sm-9">
                        <input type="text" id="lastname" name="lname" value="<?php echo $this->customer['lname']; ?>" class="form-control" autofocus required>
                        
                    </div>
			</div>
                <div class="form-group">
                    <label for="email" class="col-sm-3 control-label">* E-Mail:</label>
                    <div class="col-sm-9">
                        <input type="email" id="email" name="email" value="<?php echo $this->customer['email']; ?>" class="form-control" autofocus required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="firstName" class="col-sm-3 control-label">* Telephone:</label>
                    <div class="col-sm-9">
                        <input type="text" id="phone" name="phone" value="<?php echo $this->customer['phone']; ?>" class="form-control" autofocus required>
                    </div>
                </div>
               <div class="form-group">
                    <label for="firstName" class="col-sm-3 control-label">Fax:</label>
                    <div class="col-sm-9">
                        <input type="text" id="fax" name="fax" value="<?php echo $this->customer['fax']; ?>" class="form-control" autofocus>
                    </div>
                </div>
              
                <div class="form-group">
                    <div class="col-sm-9 col-sm-offset-3">
                        <button type="submit" class="btn btn-warning btn-block">CONTINUE</button>
                    </div>
                </div>
          
            </form>

</div>
  </div>