
				<div class="nav-top">
					<nav class="navbar navbar-default">
					
					<div class="navbar-header nav_2">
						<button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						

					</div> 
					<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
						<ul class="nav navbar-nav ">
							<li class=" active"><a href="index.html" class="hyper "><span>Home</span></a></li>	
							
							<li class="dropdown ">
								<a href="#" class="dropdown-toggle  hyper" data-toggle="dropdown" ><span>Sticker<b class="caret"></b></span></a>
								<ul class="dropdown-menu multi">
									<div class="row">
										<div class="col-sm-3" style="width:auto">
											<ul class="multi-column-dropdown">
			
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Mirrorkote</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Transparent OPP</a></li>
												<li><a href=""> <i class="fa fa-angle-right" aria-hidden="true"></i>White PP</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Simili</a></li>		
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Kraft paper</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Synthetic sticker</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Silver Foil</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Gold Foil</a></li>															
											</ul>
										
										</div>
										<div class="col-sm-3 w3l" style="width:30%">
											<a href=""><img src="public/main/images/banner.jpg" class="img-responsive" alt=""></a>
											<a href=""><img src="public/main/images/s1.jpg" class="img-responsive" alt=""></a>											
										</div>

										<div class="col-sm-3 w3l" style="width:30%">
											<a href=""><img src="public/main/images/s2.jpg" class="img-responsive" alt=""></a>
											<a href=""><img src="public/main/images/s3.jpg" class="img-responsive" alt=""></a>
										</div>

										<div class="col-sm-3 w3l" style="width:30%">
											<a href=""><img src="public/main/images/s4.jpg" class="img-responsive" alt=""></a>
										</div>
										<div class="clearfix"></div>
									</div>	
								</ul>
							</li>
							<li class="dropdown">
							
								<a href="#" class="dropdown-toggle hyper" data-toggle="dropdown" ><span>Inkjet<b class="caret"></b></span></a>
								<ul class="dropdown-menu multi multi1">
									<div class="row">
										<div class="col-sm-3" style="width:auto">
											<ul class="multi-column-dropdown">
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Banner</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Bunting</a></li>	
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Backdrop</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Rollup bunting</a></li>	
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Accessories</a></li>											
											</ul>
											
										</div>

										<div class="col-sm-3 w3l" style="width:30%">
											<a href=""><img src="public/main/images/banner.jpg" class="img-responsive" alt=""></a>
											<a href=""><img src="public/main/images/s1.jpg" class="img-responsive" alt=""></a>											
										</div>

										<div class="col-sm-3 w3l" style="width:30%">
											<a href=""><img src="public/main/images/s2.jpg" class="img-responsive" alt=""></a>
											<a href=""><img src="public/main/images/s3.jpg" class="img-responsive" alt=""></a>
										</div>

										<div class="clearfix"></div>
									</div>	
								</ul>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle hyper" data-toggle="dropdown" ><span>Business Package
								<b class="caret"></b></span></a>
								<ul class="dropdown-menu multi multi2">
									<div class="row">
										<div class="col-sm-3" style="width:auto">
											<ul class="multi-column-dropdown">
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Starter Kit</a></li>	
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Facebook post manager</a></li>		
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>T-Shirt package</a></li>
											</ul>										
										</div>

										<div class="col-sm-3 w3l" style="width:50%">
											<a href=""><img src="public/main/images/banner.jpg" class="img-responsive" alt=""></a>															
										</div>
										<div class="clearfix"></div>
									</div>	
								</ul>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle hyper" data-toggle="dropdown" ><span>Design<b class="caret"></b></span></a>
								<ul class="dropdown-menu multi multi2">
									<div class="row">
										<div class="col-sm-3" style="width:auto">
											<ul class="multi-column-dropdown">
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Logo</a></li>	
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Company Profile</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Flyers</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Brochure</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Business card</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Label Sticker</a></li>
											</ul>										
										</div>

										<div class="col-sm-3 w3l" style="width:50%">
											<a href=""><img src="public/main/images/s4.jpg" class="img-responsive" alt=""></a>															
										</div>
										<div class="clearfix"></div>
									</div>	
								</ul>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle hyper" data-toggle="dropdown" ><span>Website<b class="caret"></b></span></a>
								<ul class="dropdown-menu multi multi2">
									<div class="row">
										<div class="col-sm-3" style="width:auto">
											<ul class="multi-column-dropdown">
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Basic Package</a></li>
												
											</ul>										
										</div>
										
										
									<div class="col-sm-3 w3l" style="width:50%">
											<a href=""><img src="public/main/images/s4.jpg" class="img-responsive" alt=""></a>															
										</div>
										<div class="clearfix"></div>
									</div>	
								</ul>
							</li>
								<li class="dropdown">
								<a href="#" class="dropdown-toggle hyper" data-toggle="dropdown" ><span>T-Shirt<b class="caret"></b></span></a>
								<ul class="dropdown-menu multi multi2">
									<div class="row">
										<div class="col-sm-3" style="width:auto">
											<ul class="multi-column-dropdown">
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Cotton</a></li>	
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Jersey</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Polo</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Muslimah</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Sublimation</a></li>
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Custom</a></li>
											</ul>										
										</div>
										<div class="col-sm-3 w3l" style="width:50%">
											<a href=""><img src="public/main/images/s2.jpg" class="img-responsive" alt=""></a>															
										</div>
										
										<div class="clearfix"></div>
									</div>	
								</ul>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle hyper" data-toggle="dropdown" ><span>ID Card<b class="caret"></b></span></a>
								<ul class="dropdown-menu multi multi2">
									<div class="row">
										<div class="col-sm-3" style="width:auto">
											<ul class="multi-column-dropdown">
												<li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Package</a></li>
												
											</ul>										
										</div>										
										<div class="col-sm-3 w3l" style="width:50%">
											<a href=""><img src="public/main/images/s3.jpg" class="img-responsive" alt=""></a>															
										</div>
										<div class="clearfix"></div>
									</div>	
								</ul>
							</li>
						</ul>
					</div>
					</nav>
					 <!--<div class="cart" >
					
						<span class="fa fa-shopping-cart my-cart-icon"><span class="badge badge-notify my-cart-badge"></span></span>
					</div>-->
					<div class="clearfix"></div>
				</div>
					
				</div>			
</div>
<div class="clearfix"></div>