  <!---->
<!--<div data-vide-bg="public/main/video/video">
    <div class="container">
		<div class="banner-info">
			<h3>It is a long established fact that a reader will be distracted by 
			the readable </h3>	
			<div class="search-form">
				<form action="#" method="post">
					<input type="text" placeholder="Search..." name="Search...">
					<input type="submit" value=" " >
				</form>
			</div>		
		</div>	
    </div>
</div>

    <script>window.jQuery || document.write('<script src="public/main/js/vendor/jquery-1.11.1.min.js"><\/script>')</script>
    <script src="public/main/js/jquery.vide.min.js"></script>-->

    <!--content-->
  <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
      </ol>
      <div class="carousel-inner" role="listbox">

        <div class="item active">
         <a href=""> <img class="first-slide" src="public/main/images/banner.jpg" alt="First slide"></a>
       
        </div>
        <div class="item">
         <a href=""> <img class="second-slide " src="public/main/images/s1.jpg" alt="Second slide"></a>
         
        </div>
        <div class="item">
          <a href=""><img class="third-slide " src="public/main/images/s2.jpg" alt="Third slide"></a>
          
        </div>
        <div class="item">
         <a href=""> <img class="fourth-slide " src="public/main/images/s3.jpg" alt="Second slide"></a>
         
        </div>
        <div class="item">
          <a href=""><img class="fifth-slide " src="public/main/images/s4.jpg" alt="Third slide"></a>
          
        </div>
      </div>
    
    </div><!-- /.carousel -->

<!--content-->