<!-- navigation -->

	<div class="navigation-agileits">

		<div class="container">

			<nav class="navbar navbar-default">

							<!-- Brand and toggle get grouped for better mobile display -->

							<div class="navbar-header nav_2">

								<button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">

									<span class="sr-only">Toggle navigation</span>

									<span class="icon-bar"></span>

									<span class="icon-bar"></span>

									<span class="icon-bar"></span>

								</button>

							</div> 

							<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">								
								<ul class="nav navbar-nav">

									<li class="active"><a href="<?php echo URL;?>" class="act">Home</a></li>	

									<!-- Mega Menu -->

									<li class="dropdown">

										<a href="#" class="dropdown-toggle" data-toggle="dropdown">Sticker<b class="caret"></b></a>

										<ul class="dropdown-menu multi-column columns-3">

											<div class="row">

												<div class="multi-gd-img">

													<ul class="multi-column-dropdown">														

														<li><a href="">Mirrorkote</a></li>

														<li><a href="">Transparent OPP</a></li>

														<li><a href="">White PP</a></li>

														<li><a href="">Simili</a></li>

														<li><a href="">Kraft paper</a></li>

														<li><a href="">Synthetic sticker</a></li>
														
														<li><a href="">Silver Foil</a></li>

														<li><a href="">Gold Foil</a></li>

													</ul>

												</div>	

												

											</div>

										</ul>

									</li>

									<li class="dropdown">

										<a href="#" class="dropdown-toggle" data-toggle="dropdown">Inkjet<b class="caret"></b></a>

										<ul class="dropdown-menu multi-column columns-3">

											<div class="row">

												<div class="multi-gd-img">

													<ul class="multi-column-dropdown">														

														<li><a href="">Banner</a></li>

														<li><a href="">Bunting</a></li>

														<li><a href="">Backdrop</a></li>

														<li><a href="">Rollup bunting</a></li>

														<li><a href="">Accessories</a></li>

													</ul>

												</div>

												

												

											</div>

										</ul>

									</li>

									<li class="dropdown">

										<a href="#" class="dropdown-toggle" data-toggle="dropdown">Business Package<b class="caret"></b></a>

										<ul class="dropdown-menu multi-column columns-3">

											<div class="row">

												<div class="multi-gd-img">

													<ul class="multi-column-dropdown">														

														<li><a href="">Starter Kit</a></li>

														<li><a href="">Facebook post manager</a></li>

														<li><a href="">T-Shirt package</a></li>

													</ul>

												</div>

												

											</div>

										</ul>

									</li>

									<li class="dropdown">

										<a href="#" class="dropdown-toggle" data-toggle="dropdown">Design<b class="caret"></b></a>

										<ul class="dropdown-menu multi-column columns-3">

											<div class="row">

												<div class="multi-gd-img">

													<ul class="multi-column-dropdown">

														<li><a href="">Logo</a></li>

														<li><a href="">Company Profile</a></li>

														<li><a href="">Flyers</a></li>

														<li><a href="">Brochure</a></li>

														<li><a href="">Business card</a></li>

														<li><a href="">Label Sticker</a></li>

													</ul>

												</div>											

											</div>

										</ul>

									</li>

									<li class="dropdown">

										<a href="#" class="dropdown-toggle" data-toggle="dropdown">Website<b class="caret"></b></a>

										<ul class="dropdown-menu multi-column columns-3">

											<div class="row">

												<div class="multi-gd-img">

													<ul class="multi-column-dropdown">

														<li><a href="">Basic Package</a></li>

													</ul>

												</div>

							

											</div>

										</ul>

									</li>									

									<li class="dropdown">

										<a href="#" class="dropdown-toggle" data-toggle="dropdown">T-Shirt<b class="caret"></b></a>

										<ul class="dropdown-menu multi-column columns-3">

											<div class="row">

												<div class="multi-gd-img">

													<ul class="multi-column-dropdown">

														<li><a href="">Cotton</a></li>

														<li><a href="">Jersey</a></li>

														<li><a href="">Polo</a></li>

														<li><a href="">Muslimah</a></li>

														<li><a href="">Sublimation</a></li>

														<li><a href="">Custom</a></li>

													</ul>

												</div>											

											</div>

										</ul>

									</li>
									
									<li class="dropdown">

										<a href="#" class="dropdown-toggle" data-toggle="dropdown">ID Card<b class="caret"></b></a>

										<ul class="dropdown-menu multi-column columns-3">

											<div class="row">

												<div class="multi-gd-img">

													<ul class="multi-column-dropdown">

														<li><a href="">Package</a></li>

													</ul>

												</div>

							

											</div>

										</ul>

									</li>	
								
							    <!--<li><a href="sticker">Sticker</a></li>

									<li><a href="">Inkjet</a></li>

									<li><a href="">Design</a></li>

									<li><a href="">Website</a></li>

									<li><a href="">T-Shirt</a></li>

									<li><a href="">ID-Card</a></li>

									<li><a href="">Custom Nameset</a></li>

									<li><a href="">Packaging & Custom Print</a></li>-->

								</ul>
								
							</div>

							</nav>

			</div>

		</div>

		

<!-- //navigation -->